update flush() logic to serially empty buffer
canonical/testflinger-agent pull request #19
Opened 2023-03-02 08:41 UTC by hum4n0id

Quick patch refactor:

The previous version of flush() cleared the buffer entirely after the try block. As the dequeue is extracted via list(), the list object under iteration will potentially be shorter than the dequeue object (if messages are appended to it during list iteration). Therefore calling dequeue.clear() at the end of the list iteration will destroy messages that haven't had a chance to be sent yet.

Now we loop over the dequeue list and send and pop in the same iteration, so the buffer is sent and cleared in a serial fashion equally.

2023-03-02 21:52 UTC, plars requested changes
I think popleft() is not really what we want here though. Isn't the point here that we've flushed the buffer, so we are clearing out what's in it so that we don't just keep submitting the same thing over and over? Otherwise, if all we do is popleft(), then we'll just resubmit all the same log entries with one line removed, right?

2023-03-03 04:54 UTC, hum4n0id commented
Ah, I've actually moved the for loop outside the try block as below:

`    def flush(self):
        """Flush and post buffer"""
        for record in list(self.reqbuffer):
            try:
                self.session.post(
                    url=self.url, json=self.format(record), timeout=5
                )
            except (requests.RequestException, HTTPError) as error:
                logger.debug(error)

                return  # preserve buffer

            self.reqbuffer.popleft()`

So instead of clearing the buffer wholesale, popleft() is called in every iteration of the loop running through the queue record list.
As the queue is FIFO, we can call popleft() after every sucessful POST and it will clear that specific buffer entry that was sent out. All entries in the list will be cleared out if sent, and we are only deleting entries that have been successfully sent.
This also allows the buffer to be appended on the right without any parity issues where'd we delete records before they had a chance to be sent.

If an exception occurs, we just exit and come back the next flush cycle to continue to try and clear out the buffer.

2023-03-03 08:32 UTC, hum4n0id commented
Also helpful to note that the requests session is using _requests_retry, so we'll honor the parameters set there and retry before returning if unsuccessful.

2023-03-03 18:55 UTC, plars requested changes

2023-03-03 18:55 UTC, plars commented on testflinger_agent/__init__.py
> +        for record in list(self.reqbuffer):
Ohhh, ok that explains my confusion. I didn't catch this at first, but I think you are actually sending a new post for every single line in the log? we definitely shouldn't be doing that. The whole thing should be sent at once as a list of lines - whether it's 1 line or 50. This is why I was confused why you would want to remove them one line at a time. You will want to send the entire buffer, then definitely clear the whole thing - not send or remove them one line at a time.

2023-03-22 13:53 UTC, plars commented on testflinger_agent/__init__.py
> +        for record in list(self.reqbuffer):
@hum4n0id Are you able to take a look at the changes I requested on this? I'd really like to get this landed soon. Thanks!

2023-03-27 04:44 UTC, hum4n0id commented
The logic here would be that while it is a POST per iteration, it's still reusing the same connection/socket. This means that it's more like PUB/SUB messaging in which each log entry being its own discrete message is beneficial.

However now that we are using buffering, I can see your point. I'll modify to push out the entire buffer in a single post, and let me know your thoughts on my above comment.

2023-03-29 15:32 UTC, plars approved these changes

2023-03-29 15:32 UTC, merged